[package]
name = "tiv-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12.1"
image = "0.24.6"
ndarray = "0.15.6"
termion = "2.0.1"
